# Generated by Django 5.1.1 on 2024-12-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank=True, default='default', null=True, upload_to='static/image'),
        ),
    ]
